# Generated by Django 4.1.6 on 2023-05-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_breakfast_bimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatitems',
            name='cimage',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='combooffer',
            name='cimage',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='dimage',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='Fimage',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='freshjuice',
            name='fimage',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='limage',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
