# Generated by Django 4.1.6 on 2023-05-06 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_foodmenu_breakfast_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmenu',
            options={},
        ),
        migrations.RemoveField(
            model_name='breakfast',
            name='available',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='slug',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='fimage',
            field=models.ImageField(default=datetime.datetime(2023, 5, 6, 13, 59, 35, 441632, tzinfo=datetime.timezone.utc), upload_to='pics/'),
            preserve_default=False,
        ),
    ]
