# Generated by Django 4.1.6 on 2023-05-07 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
        migrations.AddField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2023, 5, 7, 12, 34, 25, 314401, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default=datetime.datetime(2023, 5, 7, 12, 34, 46, 42277, tzinfo=datetime.timezone.utc), max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
