# Generated by Django 4.1.6 on 2023-05-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_remove_signup_email_remove_signup_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phone_number',
        ),
    ]
